api_version = "2026-04"

[[extensions]]
name = "t:name"
handle = "deposit-checkout-validation"
type = "function"
uid = "cb3ae769-26c0-ae6f-d90c-d630132406b393644614"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.validations.generate.run"
  input_query = "src/cart_validations_generate_run.graphql"
  export = "cart-validations-generate-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"
